[package]
name = "azure-openai-service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["chat-completion", "embedding"]}
tokio = { version = "1", features = ["full"] }
futures = "0.3"
