[package]
name = "chat-store"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["chat-completion"]}
serde_json = "1"
tokio = { version = "1", features = ["full"] }
