[package]
name = "in-memory-file"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["audio"]}
tokio = { version = "1", features = ["full"] }
bytes = "1.11"
