[package]
name = "completions-stream"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["completions"]}
futures = "0.3"
tokio = { version = "1", features = ["full"] }
