[package]
name = "assistants"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
tokio = { version = "1.43.0", features = ["full"] }
tracing-subscriber = { version =  "0.3.19",  features = ["env-filter"]}
