[package]
name = "create-image-variation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["image"]}
tokio = { version = "1", features = ["full"] }
