[package]
name = "usage"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["administration"]}
tokio = { version = "1", features = ["full"] }

