[package]
name = "assistants-file-search"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = { path = "../../async-openai", features = ["assistant", "file", "vectorstore"] }
tokio = { version = "1", features = ["full"] }
