[package]
name = "create-image-edit"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai"}
tokio = { version = "1.43.0", features = ["full"] }
