[package]
name = "video"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-openai = {path = "../../async-openai", features = ["video"]}
tokio = { version = "1", features = ["full"] }
bytes = "1.11"

